/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
	// this is my second commit!
	//this is my first pull
    public boolean someLibraryMethod() {
        return true;
    }
}
